In [2]:
import pandas as pd
import numpy as np
import itertools as it
import json
import re

### Example Code:

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

#### How many negative numbers exist in the array?

In [4]:
len(a)

12

In [5]:
a[a < 0]

array([-2, -1, -6, -7])

In [12]:
a_neg = a[a < 0]

In [13]:
len(a_neg)

4

#### How many positive numbers exist in the array?

In [4]:
len(a)

12

In [8]:
a[a > 0]

array([ 4, 10, 12, 23,  3])

In [10]:
a_pos = a[a > 0]

In [11]:
len(a_pos)

5

#### How many EVEN positive numbers exist in the array?

In [14]:
a[(a > 0) & (a % 2 == 0)]

array([ 4, 10, 12])

In [15]:
a_even_pos = a[(a > 0) & (a % 2 == 0)]

In [16]:
len(a_even_pos)

3