In [2]:
import pandas as pd
import numpy as np
import itertools as it
import json
import re

### Example Code:

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

#### How many negative numbers exist in the array?

In [4]:
len(a)

12

In [5]:
a[a < 0]

array([-2, -1, -6, -7])

In [12]:
a_neg = a[a < 0]

In [13]:
len(a_neg)

4

#### How many positive numbers exist in the array?

In [4]:
len(a)

12

In [8]:
a[a > 0]

array([ 4, 10, 12, 23,  3])

In [10]:
a_pos = a[a > 0]

In [11]:
len(a_pos)

5

#### How many EVEN positive numbers exist in the array?

In [4]:
len(a)

12

In [14]:
a[(a > 0) & (a % 2 == 0)]

array([ 4, 10, 12])

In [15]:
a_even_pos = a[(a > 0) & (a % 2 == 0)]

In [16]:
len(a_even_pos)

3

#### If we add 3 to each data point, how many POSITIVE numbers would exist in the array?

In [17]:
a + 3

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [18]:
a_plus_3 = a + 3

In [19]:
a_plus_3[a_plus_3 > 0]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

In [20]:
a_plus_3_pos = a_plus_3[a_plus_3 > 0]

In [21]:
len(a_plus_3_pos)

10

#### If we squared each number, what would the mean and standard dev of the new array be?

In [23]:
a**2

array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

In [24]:
a_sq = a**2

In [25]:
a_sq.mean()

74.0

In [26]:
a_sq.std()

144.0243035046516

#### Center the data points on $\mu$ == 0

In [27]:
a.mean()

3.0

In [28]:
a - 3

array([  1,   7,   9,  20,  -5,  -4,  -3,  -3,  -3,  -9,   0, -10])

In [31]:
a_centered = a -3

In [32]:
a_centered.mean()

0.0

#### Calculate a $Z$-Score for each datapoint

## $$Z = \frac{x - \mu}{\sigma}$$

In [33]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [34]:
a.mean(),a.std()

(3.0, 8.06225774829855)

In [35]:
(a - a.mean()) / a.std()

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

#### MORE NUMPY PRACTICE

In [36]:
# Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [38]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = 0
for i in a:
    sum_of_a += i
sum_of_a

55

In [42]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = 11
for i in a:
    if i < min_of_a:
        min_of_a = i
min_of_a

1

In [43]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = 0
for i in a:
    if i > max_of_a:
        max_of_a = i
max_of_a

10

In [45]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = sum_of_a / len(a)
mean_of_a

5.5

In [46]:
'''Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers
in the above list together'''

product_of_a = 1
for i in a:
    product_of_a *= i
product_of_a

3628800

In [47]:
'''Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared 
like [1, 4, 9, 16, 25...]'''

squares_of_a = []
for i in a:
    result = i**2
    squares_of_a.append(result)
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

odds_in_a = []
for i in a